#!/bin/sh
clear
utility printHeading "ALL: \$aaa"
printf "\n"
bbb
printf "\n"
lll 5
printf "\n"
sss
printf "\n"
utility printHeading "DIFF: \$ddd"
printf "\n"
utility printHeading "COMMITS: \$ccc"
printf "\n"
utility printHeading "PROMPT: \$ppp"
