#!/bin/bash
commitsString=$(git --no-pager log --pretty=format:"%h">&1)

if [ ${#commitsString} -eq 0 ]; then
  echo "No commits found"
  exit
fi

commits=($commitsString)
commitsLength=${#commits[@]}

currentCommitIndex=0

showDiffForCommit () {
  utility clearScreen
  utility printHeading "COMMIT: \$ccc" "Use arrow keys to cycle through commit diffs, and 'q' to exit.\n"
  git --no-pager show "$1" --compact-summary
  utility printSeparator
  git --no-pager show --pretty='format:' "$1"
  utility setWindowTitle "$1 [$((commitsLength-currentCommitIndex)) of $commitsLength]"
  utility scrollToTop
}

showDiffForCommit "${commits[currentCommitIndex]}"

goLeft () {
  if [ $currentCommitIndex -gt 0 ]; then
    currentCommitIndex=$((currentCommitIndex - 1))
  fi
  showDiffForCommit "${commits[currentCommitIndex]}"
}

goRight () {
  if [ $currentCommitIndex -lt $((commitsLength - 1)) ]; then
    currentCommitIndex=$((currentCommitIndex + 1))
  fi
  showDiffForCommit "${commits[currentCommitIndex]}"
}

reset () {
  aaa
  exit
}

while : ; do
  read -r -sn1 key <&1
  case "$key" in
      A) goLeft;;
      B) goRight;;
      C) goRight;;
      D) goLeft;;
      q) reset;;
  esac
done