#!/bin/sh
commitsString=$(git --no-pager log --pretty=format:"%h">&1)

if (( ${#commitsString} == 0 )) ; then
  echo "No commits found"
  exit
fi

unset commits
while read -rd $'\n' line; do
    commits+=("$line")
done <<< "$commitsString"

commitsLength=${#commits[@]}

heading="\n\e[47m COMMIT: \$ccc \e[0m Use arrow keys to cycle through commit diffs, and 'q' to exit.\n"

currentCommitIndex=0

clearOutput () {
  clear;
  printf '\e[3J';
}

showDiffForCommit () {
  clearOutput
  printf "$heading\n"
  git --no-pager show "$1" --compact-summary
  printf "\n\e[47m\033[K\n\e[0m\n"
  git --no-pager show --pretty='format:' "$1"
  # set window title
  printf '\33]2;%s\007' "$1 [$(($commitsLength-$currentCommitIndex)) of $commitsLength]"
  utility scrollToTop
}

showDiffForCommit "${commits[currentCommitIndex]}"

go_left () {
  if (( $currentCommitIndex > 0 )) ; then
    ((currentCommitIndex--))
  fi
  showDiffForCommit "${commits[currentCommitIndex]}"
}

go_right () {
  if (( $currentCommitIndex < (${commitsLength} - 1) )) ; then
    ((currentCommitIndex++))
  fi
  showDiffForCommit "${commits[currentCommitIndex]}"
}

reset () {
  aaa
  exit
}

while : ; do
  read -r -sn1 key <&1
  case "$key" in
      A) go_left;;
      B) go_right;;
      C) go_right;;
      D) go_left;;
      q) reset;;
  esac
done
