#!/bin/sh
filesString=$(git --no-pager diff --name-only HEAD>&1);

unset files
while read -rd $'\n' line; do
    # echo "$line"
    files+=("$line")
done <<< "$filesString"

# printf "%s\n" "${files[@]}"

filesLength=${#files[@]}

# printf "${filesLength}"
# printf "${files[0]}"

if (( $filesLength == 0 )) ; then
  echo "No changes found"
  exit
fi

heading="\n\e[47m DIFF: \$ddd \e[0m \nUse arrow keys to cycle through changed file diffs, and 'q' to exit.\n"

currentFileIndex=0

clearOutput () {
  clear;
  printf '\e[3J';
}

showDiffForFile () {
  clearOutput
  printf "$heading\n"
  git status --short HEAD "$1"
  printf "\n"
  git --no-pager diff --compact-summary --color HEAD "$1"
  printf "\n"
  git --no-pager diff --minimal --color HEAD "$1"
  # TODO: find other way to scroll all the way to top - this one flickers and is macos only
  osascript <<'END'
    tell application "Terminal"
        activate
    end tell
    tell application "System Events"
        key code 126 using {command down}
    end tell
END
}

showDiffForFile "${files[currentFileIndex]}"

go_left () {
  if (( $currentFileIndex > 0 )) ; then
    ((currentFileIndex--))
  fi
  showDiffForFile "${files[currentFileIndex]}"
}

go_right () {
  if (( $currentFileIndex < (${filesLength} - 1) )) ; then
    ((currentFileIndex++))
  fi
  showDiffForFile "${files[currentFileIndex]}"
}

reset () {
  aaa
  exit
}

while : ; do
  read -r -sn1 key <&1
  case "$key" in
      A) go_left;;
      B) go_right;;
      C) go_right;;
      D) go_left;;
      q) reset;;
  esac
done
