#!/bin/sh
filesString=$(git --no-pager diff --name-only HEAD>&1);

if (( ${#filesString} == 0 )) ; then
  echo "No changes found"
  exit
fi

unset files
while read -rd $'\n' line; do
    files+=("$line")
done <<< "$filesString"

filesLength=${#files[@]}

heading="\n\e[47m DIFF: \$ddd \e[0m Use arrow keys to cycle through changed file diffs, and 'q' to exit.\n"

currentFileIndex=0

clearOutput () {
  clear;
  printf '\e[3J';
}

showDiffForFile () {
  clearOutput
  printf "$heading\n"
  git --no-pager diff --compact-summary --color HEAD "$1"
  printf "\n\e[47m\033[K\n\e[0m\n"
  git --no-pager diff --minimal --color HEAD "$1"
  utility scrollToTop
}

showDiffForFile "${files[currentFileIndex]}"

go_left () {
  if (( $currentFileIndex > 0 )) ; then
    ((currentFileIndex--))
  fi
  showDiffForFile "${files[currentFileIndex]}"
}

go_right () {
  if (( $currentFileIndex < (${filesLength} - 1) )) ; then
    ((currentFileIndex++))
  fi
  showDiffForFile "${files[currentFileIndex]}"
}

reset () {
  aaa
  exit
}

while : ; do
  read -r -sn1 key <&1
  case "$key" in
      A) go_left;;
      B) go_right;;
      C) go_right;;
      D) go_left;;
      q) reset;;
  esac
done
