#!/bin/bash
filesString=$(git --no-pager diff --name-only HEAD>&1);

if [ ${#filesString} -eq 0 ]; then
  echo "No changes found"
  exit
fi

files=($filesString)
filesLength=${#files[@]}

currentFileIndex=0

showDiffForFile () {
  utility clearScreen
  utility printHeading "DIFF: \$ddd" "Use arrow keys to cycle through changed file diffs, and 'q' to exit.\n"
  git --no-pager diff --compact-summary --color HEAD "$1"
  utility printSeparator
  git --no-pager diff --minimal --color HEAD "$1"
  # set window title
  utility setWindowTitle "$1 [$(($currentFileIndex+1)) of $filesLength]"
  utility scrollToTop
}

showDiffForFile "${files[currentFileIndex]}"

goLeft () {
  if [ $currentFileIndex -gt 0 ]; then
    currentFileIndex=$((currentFileIndex - 1))
  fi
  showDiffForFile "${files[currentFileIndex]}"
}

goRight () {
  if [ $currentFileIndex -lt $((filesLength - 1)) ]; then
    currentFileIndex=$((currentFileIndex + 1))
  fi
  showDiffForFile "${files[currentFileIndex]}"
}

reset () {
  aaa
  exit
}

while : ; do
  read -r -sn1 key <&1
  case "$key" in
      A) goLeft;;
      B) goRight;;
      C) goRight;;
      D) goLeft;;
      q) reset;;
  esac
done