#!/bin/sh
utility printHeading "LOG: \$lll \e[37m#"
if [ "x$1" == "x" ]
then
  LINES=20
else
  LINES="$1"
fi

git --no-pager log --pretty=format:'%Cblue%h %Cgreen%<(11)%cd%Cred%<(14)%cr %Creset%s %Cred%an%Creset' --date=short -$LINES

printf "\n"
