#!/bin/sh
utility printHeading "LOG: \$lll \e[37m#"

LINES=${1:-20}

git --no-pager log --pretty=format:'%Cblue%h %Cgreen%<(11)%cd%Cred%<(14)%cr %Creset%s %Cred%an%Creset' --date=short -$LINES

printf "\n"
