#!/bin/sh

scrollToTop(){
  # TODO: find other way to scroll all the way to top - "osascript" flickers and is macOS only

  if ! exists osascript; then
    exit 0
  fi

  osascript <<'END'
    tell application "Terminal"
        activate
    end tell
    tell application "System Events"
        key code 126 using {command down}
    end tell
END

}

printHeading(){
    printf "\n\e[1m\e[100m $1 \e[0m $2\n"
}

printSeparator(){
  printf "\n\e[100m\033[K\n\e[0m\n"
}

exists(){
  command -v "$1" >/dev/null 2>&1
}

"$@"