#!/bin/sh

scrollToTop(){
  if ! exists osascript; then
    return 0
  fi

  osascript <<'END'
    tell application "System Events"
        key code 115 using {command down}
    end tell
END

}

printHeading(){
  printf "\n\e[1m\e[100m $1 \e[0m $2\n"
}

printSeparator(){
  printf "\n\e[100m\033[K\n\e[0m\n"
}

exists(){
  command -v "$1" >/dev/null 2>&1
}

# https://apple.stackexchange.com/a/318217
clearScreen () {
  printf '\e[2J\e[3J\e[H'
}

setWindowTitle () {
  printf '\33]2;%s\007' "$1"
}

"$@"